### ISSUE TITLE
Nullables bug

### ISSUE THREAD

**Issue by v-jkegler** [microsoft/llguidance#11]
The algorithm in Jay Earley's original paper has a bug, which I will call the nullables bug.  We should add it to the test suite.  When the nullables bug is present, “a” is a valid input for, but is rejected by, the following grammar:

> S ′ ::= S
> S ::= AAAA
> A ::= a
> A ::= E
> E ::=

Most Earley implementations follow Earley's paper or PhD thesis, and therefore have this bug.  I expect our current implementation of the Earley algorithm also has it.

My request in this issue is only to add the test, mark it XFAIL or PASS, as appropriate, and close the issue.  I see the fix as outside the scope of this issue, and as the first step toward a roadmap which will fix this bug and lay the groundwork for, among other things:

1. Incorporating Joop Leo's speedup, which will make our implementation linear for the vast class of LR-regular grammars.
2. Supporting LR-attributed grammars, via an event mechanism.

**Comment by mmoskal** [comment]
This also passes:

```python
def test_ll_nullable_bug():
    e = string("")
    a = select([e, "a"])
    s = capture(a + a + a + a, "S")
    grm = select([s, "foo"])
    check_grammar(grm, ["", "a‧≺EOS≻"])
```

The grammar is:

```
  [1] str_n2  (Literal "foo") contextual
  [2] str_n7  (Literal "a") contextual

n0              ⇦ S  
n0              ⇦ n2  
S               ⇦ n5 n5 n5 n5   CAPTURE
n5              ⇦ ϵ  
n5              ⇦ n7  
```

**Comment by v-jkegler** [comment]
It's like we said in the meeting, there are never any bugs in your code. 🙂

Can you try it with the augment rule, S' ::= S ?  I don't think it will make a difference, but just in case.

One way of fixing the bug (although expensive, and does not lead to the new features I discussed), is to make repeated loops when building the Earley set, until no more items can be added.  Skimming the Python and Rust code, I did not see such a loop, but I might easily have missed it.  Does the current algorithm have such a loop?

Thanks,
Jeffrey

________________________________

**Comment by mmoskal** [comment]
The only way I could add the `S' ::= S` is by also adding `S' := "unrelated terminal"` (see above). But it appears to work.

**Comment by v-jkegler** [comment]
In the present implementation, you can't just stick in a new unit rule?
________________________________

**Comment by mmoskal** [comment]
The rule gets optimized away, I can disable the optimization but the grammar getting out of Guidance is somewhat more convoluted. 

BTW, for implementation I used this https://user.phil-fak.uni-duesseldorf.de/~kallmeyer/Parsing/earley.pdf

**Comment by v-jkegler** [comment]
OK.  Thanks for the fast response! -- Jeffrey
________________________________

**Comment by v-jkegler** [comment]
The Kallemeyer description looks good.  It does fix the bug.  In "Tabulation (3)" there is this line: "do until chart does not change any more:".  So it has the looping fix.

We can close this issue.  Thanks, Jeffrey

________________________________

**Comment by v-jkegler** [comment]
There are topics for investigation, but my core question is answered.  I therefore am closing this issue.

**Comment by hudson-ai** [comment]
> The Kallemeyer description looks good. It does fix the bug. In "Tabulation (3)" there is this line: "do until chart does not change any more:". So it has the looping fix. We can close this issue. Thanks, Jeffrey

I may be totally off-base (still a parsing beginner...), but this discussion looks to be talking about the [same bug mentioned in Loupe Vaillant's Earley Parsing tutorial](https://loup-vaillant.fr/tutorials/earley-parsing/empty-rules).

To steal some quotes and references from that tutorial...

That approach sounds like the one in [Grune and Jacob (1990)](http://dickgrune.com/Books/PTAPG_1st_Edition/):
> The easiest way to handle this mare’s nest is to stay calm and keep running the Predictor and Completer in turn until neither has anything more to add

If so, Loupe suggests a different fix attributed to [Aycock and Horspool (2002)](https://courses.grainger.illinois.edu/cs421/sp2012/project/PracticalEarleyParsing.pdf):
> When performing a prediction, if the predicted symbol is nullable, then advance the predictor one step.

The benefit of the second approach would be removing a layer of nesting -- not sure if there is a practical performance benefit or not though. Again, apologies if I'm off-base -- this just sounded familiar.

**Comment by v-jkegler** [comment]
Yes, what I called the nullables bug is the one being described in that quote from Grune and Jacob 1990.  Marpa takes its solution from the other quoted source: Aycock and Horspool 2002.  I did an arxiv.org article on Earley and nullables<https://arxiv.org/pdf/2303.04093>.

________________________________
